name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.40.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: msedhu1007/playwright-java-docker-test  # Replace with the URL or path to the external repository
          ref: main  # Replace with the branch or tag you want to clone

      - name: Setup Java
        uses: actions/setup-java@v2
         with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
        working-directory: playwright-java/examples/  # Set the working directory to your project

      - name: Run tests
        run: mvn test
        working-directory: playwright-java/examples/  # Set the working directory to your project
