name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.40.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: msedhu1007/playwright-java-docker-test  # Replace with the URL or path to the external repository
          ref: main  # Replace with the branch or tag you want to clone

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: List contents of workspace
        run: |
          echo "Current Directory: $(pwd)"
          ls -R  # List contents of the current directory 

      - name: Change to the external repository directory
        run: cd examples/  # Change to the directory where the external repository was cloned    

      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress

      - name: Run tests
        run: HOME=/root mvn compile exec:java -Dexec.mainClass=org.example.PageScreenshot
        working-directory: examples/  # Set the working directory to your project

      - name: Copy PNG Files to Temporary Directory
        run: |
         # Use 'find' to locate all PNG files in the current directory and its subdirectories
         find . -type f -name "*.png" -exec cp {} temp-artifacts/ \;
         shell: bash
      - name: Create ZIP Archive
        run: |
         cd temp-artifacts/
         zip -r png-artifacts.zip .
        shell: bash

      - name: Upload ZIP Archive
        uses: actions/upload-artifact@v2
        with:
         name: png-artifacts  # Specify a name for the artifact
         path: temp-artifacts/png-artifacts.zip  # Upload the ZIP archive
